-- CreateTable
CREATE TABLE "SmartAgentObjects" (
    "id" TEXT NOT NULL,
    "idSmartAgent" TEXT NOT NULL,
    "region_id" TEXT NOT NULL,
    "hierarchy_top_level" TEXT,
    "full_hierarchy" TEXT,
    "street_ids" TEXT,
    "street_cache" TEXT,
    "metro_ids" TEXT,
    "metro_cache" TEXT,
    "deal_type" TEXT,
    "holding_period_in_years" TEXT,
    "rooms" TEXT,
    "price" TEXT,
    "agent_commission" TEXT,
    "client_commission" TEXT,
    "floor" TEXT,
    "floors" TEXT,
    "distance" TEXT,
    "transport" TEXT,
    "period" TEXT,
    "building" TEXT,
    "corpus" TEXT,
    "hometype" TEXT,
    "total_area" TEXT,
    "living_area" TEXT,
    "kitchen_area" TEXT,
    "land_area" TEXT,
    "remont" TEXT,
    "fridge" TEXT,
    "washer" TEXT,
    "sell_balcony" TEXT,
    "tv" TEXT,
    "slavs" TEXT,
    "rf" TEXT,
    "children" TEXT,
    "pets" TEXT,
    "furniture" TEXT,
    "isolated" TEXT,
    "view_from_windows" TEXT,
    "wc" TEXT,
    "checked_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "user_id_who_created" TEXT,
    "order_for_user_id" TEXT,
    "name" TEXT,
    "note" TEXT,
    "owner" TEXT,
    "lon" TEXT,
    "lat" TEXT,
    "alternatives" TEXT,
    "edit_hash" TEXT,
    "new_building" TEXT,
    "feed_export_enabled" TEXT,
    "images_source" TEXT[],
    "images" TEXT[],
    "images_ids" TEXT[],
    "note_generated" TEXT,

    CONSTRAINT "SmartAgentObjects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SmartAgentObjects_idSmartAgent_key" ON "SmartAgentObjects"("idSmartAgent");
